1laba
SolomiaKukharuk/programming1 pull request #1
Opened 2023-09-10 16:09 UTC by SolomiaKukharuk

2023-09-11 12:10 UTC, davendiy commented
краще зробіть всі файли в окремій папці Lab1

2023-09-11 12:11 UTC, davendiy commented
і тоді можна всю папку одним комітом додати

2023-09-12 06:49 UTC, davendiy commented on 1.10
Не використовуйте синтаксис `"%0.2f" % x`. Це застаріла штука ще з другого пайтона. Замість цього краще `"{x:.2f}"`

2023-09-12 06:51 UTC, davendiy requested changes
Зробіть однією папкою і можна мерджити

2023-09-12 06:51 UTC, davendiy commented on 1.9
> +print("%0.0f %0.0f" % (grn,cop))
от де ви вже нагуглили цей синтаксис?

2023-09-12 07:32 UTC, SolomiaKukharuk commented
Вибачте,  не знайшла, як можна перемістити все в одну парку.

On Mon, 11 Sept 2023, 15:11 davendiy, ***@***.***> wrote:

> і тоді можна всю папку одним комітом додати
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SolomiaKukharuk/programming1/pull/1#issuecomment-1713754053>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCMIM6QXP62WURTTHOZFYVTXZ35X7ANCNFSM6AAAAAA4SIQADU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-12 13:27 UTC, davendiy commented
не бачу як це можна переробити з графічного інтерфейсу. Створіть нову гілку з назвою lab1_v2, і завантажте одразу папку з всіма лабами з назвою lab1. Це можна зробити через add_files, просто одразу папку скидуєте, а не окремо файл

2023-09-15 13:10 UTC, davendiy commented
Змінив вам всю структуру, тепер можна мерджити

2023-09-15 14:26 UTC, merged